version: '2.1'

x-logging:
  &default-logging
  options:
    max-size: '12m'
    max-file: '5'
  driver: json-file

networks:
  default:
    driver: bridge

volumes:
  traefik-ssl:
    driver: local
  sortoe-db-data:
    driver: local
  sortoe-static:
    driver: local

services:

  traefik:
    extends:
      file: docker-traefik/docker-compose.yml
      service: traefik
    volumes:
      - traefik-ssl:/ssl
    restart: always
    ports:
      - 65080:65080
      - 65443:65443
    networks:
      - default
    environment:
      REST_PORT: "7080"
      HTTP_PORT: "65080"
      HTTPS_PORT: "65443"
      EMAIL: "devops@sofwerx.org"
      DNS_DOMAIN: ${DNS_DOMAIN}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_HOSTED_ZONE_ID: ${AWS_HOSTED_ZONE_ID}
    logging: *default-logging
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.port=7080"
      - "traefik.frontend.rule=Host:traefik.${DNS_DOMAIN}"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.entryPoints=http,https"

  sortoe-nginx:
    image: 212171213234.dkr.ecr.us-east-1.amazonaws.com/sortoe/nginx:0.3.0
    depends_on:
      - sortoe-service-1.0.0
      - sortoe-web
    container_name: sortoe-nginx
    hostname: sortoe-nginx
    networks:
      - default
    logging: *default-logging
    labels:
      - "traefik.enable=true"
      - "traefik.backend=sortoe-nginx"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:sortoe.${DNS_DOMAIN}"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.entryPoints=http,https"

  sortoe-web:
    build:
      context: docker-sortoe/
      dockerfile: Dockerfile.web
    image: sortoe-web
    container_name: sortoe-web
    hostname: sortoe-web
    networks:
      - default
    environment:
      SORTOE_API_URL: https://sortoe.${DNS_DOMAIN}/v1.0.0
      SORTOE_API_VERSION: 1.0.0
      SORTOE_DATASERVICE_HOST: sortoe.${DNS_DOMAIN}
      SORTOE_GRAPHQL_URL: https://sortoe.${DNS_DOMAIN}/v1.0.0/graphiql
      NODE_ENV: production
      PUBLIC_URL: https://sortoe.${DNS_DOMAIN}
      #REGISTER_SERVICE_WORKER: 'false'
    logging: *default-logging
    labels:
      - "traefik.enable=true"
      - "traefik.backend=sortoe-web"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:sortoe-web.${DNS_DOMAIN}"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.entryPoints=http,https"

  sortoe-service-1.0.0:
    image: 212171213234.dkr.ecr.us-east-1.amazonaws.com/sortoe/dataservice:1.0.0-b2
    depends_on:
      - sortoe-db
    container_name: sortoe-service-1.0.0
    hostname: sortoe-service-1.0.0
    networks:
      - default
    environment:
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://${SORTOE_POSTGRES_USER}:${SORTOE_POSTGRES_PASSWORD}@sortoe-db:5432/sortoe
      - DATABASE_TEST_URL=postgres://${SORTOE_POSTGRES_USER}:${SORTOE_POSTGRES_PASSWORD}@sortoe-db:5432/sortoe-test
    volumes:
      - sortoe-static:/var/sortoe
    logging: *default-logging
    labels:
      - "traefik.enable=true"
      - "traefik.backend=sortoe-service"
      - "traefik.port=5000"
      - "traefik.frontend.rule=Host:sortoe-service.${DNS_DOMAIN}"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.entryPoints=http,https"

  sortoe-db:
    image: 212171213234.dkr.ecr.us-east-1.amazonaws.com/sortoe/db:latest
    container_name: sortoe-db
    hostname: sortoe-db
    networks:
      - default
    environment:
      POSTGRES_USER: ${SORTOE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SORTOE_POSTGRES_PASSWORD}
    healthcheck:
      test: exit 0
    volumes:
      - sortoe-db-data:/var/lib/postgresql/data
    logging: *default-logging
    labels:
      - "traefik.enable=false"

