version: "2"

networks: 
  default:
    driver: bridge

volumes:
  traefik-ssl:
    driver: local
  mariadb-data:
    driver: local
  moodle-data:
    driver: local

services:

  traefik:
    extends:
      file: docker-traefik/docker-compose.yml
      service: traefik
    container_name: traefik
    hostname: traefik
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - default
    environment:
      REST_PORT: "7080"
      HTTP_PORT: "80"
      HTTPS_PORT: "443"
      EMAIL: "devops@sofwerx.org"
      DNS_DOMAIN: ${DNS_DOMAIN}
      SUBDOMAINS: ${SUBDOMAINS}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.port=7080"
      - "traefik.frontend.rule=Host:traefik.${DNS_DOMAIN}"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.entryPoints=http,https"

  mariadb:
    image: mariadb:10.2.12
    container_name: mariadb
    hostname: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_MOODLE_DATABASE}
      MYSQL_USER: ${MYSQL_MOODLE_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_MOODLE_PASSWORD}
    volumes:
      - 'mariadb-data:/var/lib/mysql'
    labels:
      - "traefik.enable=false"

  moodle:
    build:
      context: docker-moodle/
      dockerfile: Dockerfile
    image: 'sofwerx/moodle'
    container_name: moodle
    hostname: moodle
    volumes:
     - "moodle-data:/var/moodledata"
    environment:
      DB_ENV_MYSQL_DATABASE: ${MYSQL_MOODLE_DATABASE}
      DB_ENV_MYSQL_USER: ${MYSQL_MOODLE_USERNAME}
      DB_ENV_MYSQL_PASSWORD: ${MYSQL_MOODLE_PASSWORD}
      DB_PORT_3306_TCP_ADDR: mariadb
      DB_PORT_3306_TCP_PORT: 3306
      MOODLE_URL: https://${DNS_DOMAIN}
    depends_on:
      - mariadb
    labels:
      - "traefik.enable=true"
      - "traefik.backend=moodle"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:${DNS_DOMAIN}"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.entryPoints=http,https"

