version: '2.1'

x-logging:
  &default-logging
  options:
    max-size: '12m'
    max-file: '5'
  driver: json-file

networks:
  default:
    driver: bridge

volumes:
  traefik-ssl:
    driver: local

  jira-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/jira
  jira-postgres-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/jira-postgres

services:

  traefik:
    extends:
      file: docker-traefik/docker-compose.yml
      service: traefik
    volumes:
      - traefik-ssl:/ssl
    restart: always
    ports:
      - 80:60080
      - 443:60443
      - 60080:60080
      - 60443:60443
    networks:
      - default
    environment:
      REST_PORT: "7080"
      HTTP_PORT: "60080"
      HTTPS_PORT: "60443"
      EMAIL: "devops@sofwerx.org"
      DNS_DOMAIN: ${DNS_DOMAIN}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_HOSTED_ZONE_ID: ${AWS_HOSTED_ZONE_ID}
    logging: *default-logging
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.port=7080"
      - "traefik.frontend.rule=Host:traefik.${DNS_DOMAIN}"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.entryPoints=http,https"

  jira:
    container_name: jira
    hostname: jira
    build:
      context: docker-jira/
      args:
        JIRA_VERSION: ${JIRA_VERSION}
    image: sofwerx/jira:${JIRA_VERSION}
    networks:
      - default
    volumes:
      - jira-data:/var/atlassian/jira
    environment:
      JIRA_DATABASE_URL: postgresql://${JIRA_DB_USER}@jira-postgres/${JIRA_DB_NAME}
      JIRA_DB_PASSWORD: ${JIRA_DB_PASSWORD}
      SETENV_JVM_MINIMUM_MEMORY: 256m
      SETENV_JVM_MAXIMUM_MEMORY: 4g
      #JIRA_PROXY_NAME:
      #JIRA_PROXY_PORT:
      #JIRA_PROXY_SCHEME:
    logging: *default-logging
    labels:
      com.blacklabelops.description: "Atlassian Jira"
      com.blacklabelops.service: "jira"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=jira"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:jira.${DNS_DOMAIN}"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.entryPoints=http,https"

  jira-postgres:
    container_name: jira-postgres
    hostname: jira-postgres
    build:
      context: docker-jira-postgres/
      args:
        POSTGRES_VERSION: ${JIRA_DB_VERSION}
    image: sofwerx/jira-postgres:${JIRA_DB_VERSION}
    networks:
      - default
    volumes:
      - jira-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${JIRA_DB_USER}
      POSTGRES_PASSWORD: ${JIRA_DB_PASSWORD}
      POSTGRES_DB: ${JIRA_DB_NAME}
      POSTGRES_ENCODING: UNICODE
      POSTGRES_COLLATE: C
      POSTGRES_COLLATE_TYPE: C
    logging: *default-logging
    labels:
      com.blacklabelops.description: "PostgreSQL Database Server"
      com.blacklabelops.service: "postgresql"
    labels:
      - "traefik.enable=false"

