version: '3.1'

volumes:
  minio0-data:

  minio1-data:

  minio2-data:

  minio3-data:

  minio4-data:

  minio5-data:

  minio6-data:

  minio7-data:

networks:

  minio:
    driver: overlay

secrets:

  secret_key:
    external: true

  access_key:
    external: true

services:

  minio0:
    image: minio/minio:RELEASE.2018-03-30T00-38-44Z
    volumes:
      - minio0-data:/export
    ports:
      - "9000:9000"
    networks:
      - minio
    deploy:
      placement:
        constraints:
        - "node.hostname == swx-u-ub-orange0"
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      labels:
        - "traefik.enable=true"
        - "traefik.backend=minio"
        - "traefik.port=9000"
        - "traefik.frontend.rule=Host:minio.${DNS_DOMAIN}"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.frontend.entryPoints=http,https"
    command: server http://minio0:9000/export http://minio1:9000/export http://minio2:9000/export http://minio3:9000/export http://minio4:9000/export http://minio5:9000/export http://minio6:9000/export http://minio7:9000/export
    secrets:
      - secret_key
      - access_key

  minio1:
    image: minio/minio:RELEASE.2018-03-30T00-38-44Z
    volumes:
      - minio1-data:/export
    ports:
      - "9001:9000"
    networks:
      - minio
    deploy:
      placement:
        constraints:
        - "node.hostname == swx-u-ub-orange1"
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      labels:
        - "traefik.enable=true"
        - "traefik.backend=minio"
        - "traefik.port=9000"
        - "traefik.frontend.rule=Host:minio.${DNS_DOMAIN}"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.frontend.entryPoints=http,https"
    command: server http://minio0:9000/export http://minio1:9000/export http://minio2:9000/export http://minio3:9000/export http://minio4:9000/export http://minio5:9000/export http://minio6:9000/export http://minio7:9000/export
    secrets:
      - secret_key
      - access_key

  minio2:
    image: minio/minio:RELEASE.2018-03-30T00-38-44Z
    volumes:
      - minio2-data:/export
    ports:
      - "9002:9000"
    networks:
      - minio
    deploy:
      placement:
        constraints:
        - "node.hostname == swx-u-ub-orange2"
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      labels:
        - "traefik.enable=true"
        - "traefik.backend=minio"
        - "traefik.port=9000"
        - "traefik.frontend.rule=Host:minio.${DNS_DOMAIN}"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.frontend.entryPoints=http,https"
    command: server http://minio0:9000/export http://minio1:9000/export http://minio2:9000/export http://minio3:9000/export http://minio4:9000/export http://minio5:9000/export http://minio6:9000/export http://minio7:9000/export
    secrets:
      - secret_key
      - access_key

  minio3:
    image: minio/minio:RELEASE.2018-03-30T00-38-44Z
    volumes:
      - minio3-data:/export
    ports:
      - "9003:9000"
    networks:
      - minio
    deploy:
      placement:
        constraints:
        - "node.hostname == swx-u-ub-orange3"
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      labels:
        - "traefik.enable=true"
        - "traefik.backend=minio"
        - "traefik.port=9000"
        - "traefik.frontend.rule=Host:minio.${DNS_DOMAIN}"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.frontend.entryPoints=http,https"
    command: server http://minio0:9000/export http://minio1:9000/export http://minio2:9000/export http://minio3:9000/export http://minio4:9000/export http://minio5:9000/export http://minio6:9000/export http://minio7:9000/export
    secrets:
      - secret_key
      - access_key

  minio4:
    image: minio/minio:RELEASE.2018-03-30T00-38-44Z
    volumes:
      - minio4-data:/export
    ports:
      - "9004:9000"
    networks:
      - minio
    deploy:
      placement:
        constraints:
        - "node.hostname == swx-u-ub-orange4"
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      labels:
        - "traefik.enable=true"
        - "traefik.backend=minio"
        - "traefik.port=9000"
        - "traefik.frontend.rule=Host:minio.${DNS_DOMAIN}"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.frontend.entryPoints=http,https"
    command: server http://minio0:9000/export http://minio1:9000/export http://minio2:9000/export http://minio3:9000/export http://minio4:9000/export http://minio5:9000/export http://minio6:9000/export http://minio7:9000/export
    secrets:
      - secret_key
      - access_key

  minio5:
    image: minio/minio:RELEASE.2018-03-30T00-38-44Z
    volumes:
      - minio5-data:/export
    ports:
      - "9005:9000"
    networks:
      - minio
    deploy:
      placement:
        constraints:
        - "node.hostname == swx-u-ub-orange5"
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      labels:
        - "traefik.enable=true"
        - "traefik.backend=minio"
        - "traefik.port=9000"
        - "traefik.frontend.rule=Host:minio.${DNS_DOMAIN}"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.frontend.entryPoints=http,https"
    command: server http://minio0:9000/export http://minio1:9000/export http://minio2:9000/export http://minio3:9000/export http://minio4:9000/export http://minio5:9000/export http://minio6:9000/export http://minio7:9000/export
    secrets:
      - secret_key
      - access_key

  minio6:
    image: minio/minio:RELEASE.2018-03-30T00-38-44Z
    volumes:
      - minio6-data:/export
    ports:
      - "9006:9000"
    networks:
      - minio
    deploy:
      placement:
        constraints:
        - "node.hostname == swx-u-ub-orange6"
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      labels:
        - "traefik.enable=true"
        - "traefik.backend=minio"
        - "traefik.port=9000"
        - "traefik.frontend.rule=Host:minio.${DNS_DOMAIN}"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.frontend.entryPoints=http,https"
    command: server http://minio0:9000/export http://minio1:9000/export http://minio2:9000/export http://minio3:9000/export http://minio4:9000/export http://minio5:9000/export http://minio6:9000/export http://minio7:9000/export
    secrets:
      - secret_key
      - access_key

  minio7:
    image: minio/minio:RELEASE.2018-03-30T00-38-44Z
    volumes:
      - minio7-data:/export
    ports:
      - "9007:9000"
    networks:
      - minio
    deploy:
      placement:
        constraints:
        - "node.hostname == swx-u-ub-orange7"
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      labels:
        - "traefik.enable=true"
        - "traefik.backend=minio"
        - "traefik.backend.loadbalancer.method=wrr"
        - "traefik.port=9000"
        - "traefik.frontend.rule=Host:minio.${DNS_DOMAIN}"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.frontend.entryPoints=http,https"
    command: server http://minio0:9000/export http://minio1:9000/export http://minio2:9000/export http://minio3:9000/export http://minio4:9000/export http://minio5:9000/export http://minio6:9000/export http://minio7:9000/export
    secrets:
      - secret_key
      - access_key

