version: "3.4"

networks:

  consul:
    driver: overlay
    driver_opts:
      encrypted: "true"
    ipam:
      driver: default
      config:
        - subnet: 172.29.20.0/28

services:

  multiarch:
    hostname: multiarch
    container_name: multiarch
    image: multiarch/qemu-user-static:register
    command: --reset
    privileged: true
    networks:
      - consul


