# https://github.com/severalnines/galera-docker-mariadb
# https://severalnines.com/blog/mysql-docker-deploy-homogeneous-galera-cluster-etcd

version: '3.4'

networks:

  orange_default:
    external:
      name: orange_default

services:

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    hostname: adminer
    ports:
      - 18080:8080
    networks:
      - orange_default
    labels:
      - "traefik.enable=true"
      - "traefik.backend=adminer"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:adminer.${DNS_DOMAIN}"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.entryPoints=http,https"

