version: "3.3"

networks:

  traefik:
    driver: overlay
    driver_opts:
      encrypted: "true"

services:

  traefik:
    hostname: traefik
    build: traefik/
    image: sofwerx/traefik
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      HTTP_PORT: "80"
      HTTPS_PORT: "443"
      REST_PORT: "8080"
      EMAIL: "devops@sofwerx.org"
      DNS_DOMAIN: ${DNS_DOMAIN}
      SUBDOMAINS: ${SUBDOMAINS}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --docker --docker.swarmmode --docker.domain=${DNS_DOMAIN} --docker.watch
    networks:
      - traefik
    deploy:
      mode: global
      placement:
        constraints:
          - "node.role == manager"
      labels:
        - "traefik.backend=traefik"
        - "traefik.backend.loadbalancer.swarm=true"
        - "traefik.port=8080"
        - "traefik.frontend.rule=Host:traefik.${DNS_DOMAIN}"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.frontend.entryPoints=http,https"


