version: '2.1'

x-logging:
  &default-logging
  options:
    max-size: '12m'
    max-file: '5'
  driver: json-file

networks: 

  default:
    driver: bridge

volumes:

  traefik-ssl:
    driver: local
  domoticz-backups:
    driver: local
  domoticz-db:
    driver: local
  domoticz-scripts:
    driver: local
  motion-data:
    driver: local

services:

  traefik:
    extends:
      file: docker-traefik/docker-compose.yml
      service: traefik
    restart: always
    ports:
      - 21080:21080
      - 21443:21443
    networks:
      - default
    environment:
      REST_PORT: "7080"
      HTTP_PORT: "21080"
      HTTPS_PORT: "21443"
      EMAIL: "devops@sofwerx.org"
      DNS_DOMAIN: ${DNS_DOMAIN}
      SUBDOMAINS: ${SUBDOMAINS}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
    logging: *default-logging
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.port=7080"
      - "traefik.frontend.rule=Host:traefik.${DNS_DOMAIN}"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.entryPoints=http,https"

#  ethminer:
#    build: docker-ethminer/
#    image: sofwerx/ethminer:${ARCH}
#    container_name: ethminer
#    hostname: ethminer
#    restart: always
#    environment:
#      GPU_FORCE_64BIT_PTR: 0
#      GPU_MAX_HEAP_SIZE: 100
#      GPU_USE_SYNC_OBJECTS: 1
#      GPU_MAX_ALLOC_PERCENT: 100
#      GPU_SINGLE_ALLOC_PERCENT: 100
#    command: /ethminer/build/ethminer/ethminer --cuda-parallel-hash 8 --farm-recheck 200 -U -S us1.ethermine.org:4444 -FS us2.ethermine.org:4444 -O 2c0859b9312d9bf93e1b4cae8d47d59030a75a9f.${DOCKER_MACHINE_NAME}
#    logging: *default-logging
#    labels:
#      - "traefik.enable=false"

#  xmr-stak:
#    container_name: xmr-stak
#    hostname: xmr-stak
#    build: xmr-stak/
#    image: sofwerx/xmr-stak:${ARCH}
#    restart: always
#    environment:
#      NVIDIA_VISIBLE_DEVICES: ""
#    command: nice -n +20 xmr-stak --currency monero -o pool.minexmr.com:7777 -u 46UBBUKUst1LPLKsQCfu6p1HkXAPPAD1vbEPCpKfgE7Ma7NJYzLGbhcTYP7o1mRygU8cFKrzyghUxFFLpBQ3ERXKC83zkVY.${DOCKER_MACHINE_NAME} -p x
#    tty: true
#    labels:
#      - "traefik.enable=false"

#  ravencoin-gpu-ccminer:
#    extends:
#      file: docker-ravencoin/docker-compose.yml
#      service: ravencoin-gpu-ccminer
#    restart: always
#    environment:
#      URL: ${URL}
#      USERNAME: ${USERNAME}
#      PASSWORD: ${DOCKER_MACHINE_NAME}
#    labels:
#      - "traefik.enable=false"

  domoticz:
    extends:
      file: docker-domoticz/docker-compose.yml
      service: domoticz
    restart: always
    privileged: true
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    labels:
      - "traefik.enable=true"
      - "traefik.backend=domoticz"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:domoticz.${DNS_DOMAIN}"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.entryPoints=http,https"

  es-domoticz-notify:
    extends:
      file: es-domoticz-notify/docker-compose.yml
      service: es-domoticz-notify
    restart: always
    environment:
      ES_URL: ${ES_DOMOTICZ_URL}
      ES_HTTP_AUTH: ${ES_DOMOTICZ_HTTP_AUTH}
    ports:
      - 3000:3000
    labels:
      - "traefik.enable=true"
      - "traefik.backend=es-domoticz-notify"
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host:es-domoticz-notify.${DNS_DOMAIN}"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.entryPoints=http,https"

  es-ifttt:
    extends:
      file: es-ifttt/docker-compose.yml
      service: es-ifttt
    restart: always
    environment:
      ES_URL: ${ES_DOMOTICZ_URL}
      ES_HTTP_AUTH: ${ES_DOMOTICZ_HTTP_AUTH}
    ports:
      - 21001:3000
    labels:
      - "traefik.enable=true"
      - "traefik.backend=es-ifttt"
      - "traefik.port=21001"
      - "traefik.frontend.rule=Host:es-ifttt.${DNS_DOMAIN}"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.entryPoints=http,https"

  motion:
    extends:
      file: docker-motion/docker-compose.yml
      service: motion
    image: sofwerx/motion
    restart: always
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      RTSP_URL: ${RTSP_URL}
      RTSP_AUTH: ${RTSP_AUTH}
      ES_MOTION_URL: ${ES_MOTION_URL}
      ES_MOTION_HTTP_AUTH: ${ES_MOTION_HTTP_AUTH}
      FRAMERATE: 7
    volumes:
      - motion-data:/data
    logging: *default-logging
    networks:
      - default
    labels:
      - "traefik.enable=false"

