version: "2.1"

networks: 

  default:
    driver: bridge

volumes:

  osh-db:
    driver: local
  osh-logs:
    driver: local

services:
  osh-core:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: osh-core
    hostname: osh-core
    restart: always
    volumes:
      - osh-logs:/data/logs
      - osh-db:/data/db
    networks:
      - default
    ports:
      - 8181:8181

