version: "2.1"

networks: 

  default:
    driver: bridge

volumes:

  osh-core:
    driver: local

services:
  osh-core:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: osh-core
    hostname: osh-core
    restart: always
    networks:
      - default
    ports:
      - 8181:8181

