version: "3.4"

x-logging:
  &default-logging
  options:
    max-size: '12m'
    max-file: '5'
  driver: json-file

volumes:

  registry-data:
    driver: local
  registry-certs:
    driver: local
  registry-auth:
    driver: local

services:

  registry:
    hostname: registry
    image: registry:2
    environment:
      REGISTRY_HTTP_SECRET: ${REGISTRY_HTTP_SECRET}
#      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
#      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
#      REGISTRY_AUTH: htpasswd
#      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
#      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - registry-data:/var/lib/registry
      - registry-certs:/certs
      - registry-auth:/auth
    logging: *default-logging
    deploy:
      mode: replicated
      endpoint_mode: vip
      replicas: 1
      placement:
        constraints:
          - "node.hostname == swx-u-ub-shuttlex0"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.backend=registry"
        - "traefik.backend.loadbalancer.swarm=true"
        - "traefik.backend.loadbalancer.method=wrr"
        - "traefik.port=5000"
        - "traefik.frontend.rule=Host:registry.${DNS_DOMAIN}"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.frontend.entryPoints=http,https"

