version: '2'

networks: {}

volumes:
  traefik-ssl:
    driver: local
  rcloud-data:
    driver: local
  rcloud-conf:
    driver: local
  redis-data:
    driver: local
  solr-data:
    driver: local
  solr-conf:
    driver: local

services:

  traefik:
    container_name: traefik
    hostname: traefik
    build: traefik/
    image: swx-traefik
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      HTTP_PORT: "80"
      HTTPS_PORT: "443"
      REST_PORT: "8080"
      EMAIL: "ian@sofwerx.org"
      DNS_DOMAIN: "rcloud-dev.devwerx.org"
      SUBDOMAINS: '"rcloud-dev.devwerx.org", "traefik.rcloud-dev.devwerx.org"'
    volumes:
      - traefik-ssl:/ssl
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - rcloud
    labels:
      - "traefik.backend=traefik"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:traefik.rcloud-dev.devwerx.org"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.entryPoints=http,https"

  redis:
    container_name: redis
    hostname: redis
    restart: always
    image: redis:3
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    labels:
      - "traefik.enable=false"

  solr:
    build: rcloud/
    image: rcloud
    restart: always
    container_name: solr
    hostname: solr
    volumes:
      - solr-data:/data/rcloud/services/solr/example/solr/rcloudnotebooks/data
      - solr-conf:/data/rcloud/services/solr/example/solr/rcloudnotebooks/conf
    command: /data/rcloud/services/solr/bin/solr start -f
    labels:
      - "traefik.enable=false"

  rcloud:
    build: rcloud/
    image: rcloud
    restart: always
    container_name: rcloud
    hostname: rcloud
    volumes:
      - rcloud-data:/data/rcloud/data
      - rcloud-conf:/data/rcloud/conf
    environment:
      FQDN: rcloud-dev.devwerx.org
      SOLR_HOST: solr
      REDIS_HOST: redis
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GITHUB_USER_WHITELIST: ${GITHUB_USER_WHITELIST}
    ports:
      - 8080:8080
    depends_on:
      - redis
      - solr
    labels:
      - "traefik.backend=rcloud"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:rcloud-dev.devwerx.org"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.entryPoints=http,https"

