version: "2.1"

networks: 
  default:
    driver: bridge

volumes:
  traefik-ssl:
    driver: local
  mariadb-data:
    driver: local
  magento-data:
    driver: local

services:

  traefik:
    extends:
      file: docker-traefik/docker-compose.yml
      service: traefik
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - default
    environment:
      REST_PORT: "7080"
      HTTP_PORT: "80"
      HTTPS_PORT: "443"
      EMAIL: "devops@sofwerx.org"
      DNS_DOMAIN: ${DNS_DOMAIN}
      SUBDOMAINS: ${SUBDOMAINS}
#      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
#      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
#      AWS_REGION: ${AWS_REGION}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.port=7080"
      - "traefik.frontend.rule=Host:traefik.${DNS_DOMAIN}"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.entryPoints=http,https"

  mariadb:
    image: 'bitnami/mariadb:latest'
    container_name: mariadb
    hostname: mariadb
    restart: always
    networks:
      - default
    environment:
      MARIADB_ROOT_USER: ${MARIADB_ROOT_USER}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MAGENTO_DATABASE_USER}
      MARIADB_PASSWORD: ${MAGENTO_DATABASE_PASSWORD}
      MARIADB_DATABASE: ${MAGENTO_DATABASE_NAME}
      MARIADB_EXTRA_FLAGS: '--max-connect-errors=1000 --max_connections=155'
    volumes:
      - 'mariadb-data:/bitnami'
    restart: always
    healthcheck:
      test: mysqladmin -h localhost -u $${MAGENTO_DATABASE_USER} -p$${MAGENTO_DATABASE_PASSWORD} ping
      timeout: 20s
      retries: 10
    labels:
      - "traefik.enable=false"

  magento:
    image: 'bitnami/magento:latest'
    container_name: magento
    hostname: magento
    networks:
      - default
    environment:
      MARIADB_HOST: mariadb
      MARIADB_PORT_NUMBER: "3306"
      MAGENTO_DATABASE_USER: ${MAGENTO_DATABASE_USER}
      MAGENTO_DATABASE_PASSWORD: ${MAGENTO_DATABASE_PASSWORD}
      MAGENTO_DATABASE_NAME: ${MAGENTO_DATABASE_NAME}
      MAGENTO_HOST: magento.${DNS_DOMAIN}
      MAGENTO_USERNAME: ${MAGENTO_USERNAME}
      MAGENTO_PASSWORD: ${MAGENTO_PASSWORD}
      MAGENTO_EMAIL: ${MAGENTO_EMAIL}
    volumes:
      - 'magento-data:/bitnami'
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=magento"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:magento.${DNS_DOMAIN}"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.entryPoints=http,https"

