version: "3.3"

volumes:
  datahub-data:
    driver: local

services:

  datahub:
    build: .
    volumes:
      - "datahub-data:/data"
    ports:
      - "7997:7997"
      - "7999:7999"
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8040:8040"
      - "8041:8041"
      - "8042:8042"
      - "8043:8043"
      - "8044:8044"

