version: "2.1"

x-logging:
  &default-logging
  options:
    max-size: '12m'
    max-file: '5'
  driver: json-file

networks: 
  default:
    driver: bridge

volumes:
  traefik-ssl:
    driver: local
  neo4j-data:
    driver: local

services:

  glo:
    extends:
      file: glo/docker-compose.yml
      service: glo
    image: sofwerx/glo
    container_name: glo
    hostname: glo
    restart: always
    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.backend=glo"
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host:glo.${DNS_DOMAIN}"
      - "traefik.frontend.passHostHeader=false"
      - "traefik.frontend.entryPoints=http,https"


#  glo-demo:
#    extends:
#      file: glo-demo/docker-compose.yml
#      service: glo-demo
#    image: sofwerx/glo-demo
#    container_name: glo-demo
#    hostname: glo-demo
#    restart: always
#    networks:
#      - default
#    labels:
#      - "traefik.enable=true"
#      - "traefik.backend=glo-demo"
#      - "traefik.port=4200"
#      - "traefik.frontend.rule=Host:glo-demo.${DNS_DOMAIN}"
#      - "traefik.frontend.passHostHeader=false"
#      - "traefik.frontend.entryPoints=http,https"

  traefik:
    extends:
      file: docker-traefik/docker-compose.yml
      service: traefik
    restart: always
    ports:
      - 20080:20080
      - 20443:20443
    networks:
      - default
    environment:
      REST_PORT: "7080"
      HTTP_PORT: "20080"
      HTTPS_PORT: "20443"
      EMAIL: "devops@sofwerx.org"
      DNS_DOMAIN: ${DNS_DOMAIN}
      SUBDOMAINS: ${SUBDOMAINS}
    logging: *default-logging
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.port=7080"
      - "traefik.frontend.rule=Host:traefik.${DNS_DOMAIN}"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.entryPoints=http,https"

  neo4j:
    extends:
      file: docker-neo4j/docker-compose.yml
      service: neo4j
    image: neo4j:latest
    restart: always
    networks: 
      - default
    ports:
      - 7687:7687
      - 7474:7474
      - 7473:7473
    volumes:
      - traefik-ssl:/ssl
      - neo4j-data:/var/lib/neo4j
    labels:
      - "traefik.enable=true"
      - "traefik.backend=neo4j"
      - "traefik.port=7474"
      - "traefik.frontend.rule=Host:neo4j.${DNS_DOMAIN}"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.entryPoints=http,https"

